---
- name: restart supervisor
  supervisorctl: name=mezzanine-example:gunicorn_mezzanine-example state=restarted
  sudo: True
- name: restart nginx
  service: name=nginx state=restarted
  sudo: True
