---
- name: deploy postgres on vagrant
  hosts: db
  vars_files:
    - secrets.yml
  roles:
    - role: database
      database_name: "{{ mezzanine_proj_name }}"
      database_user: "{{ mezzanine_proj_name }}"

- name: deploy mezzanine on vagrant
  hosts: web
  vars_files:
    - secrets.yml

  roles:
    - role: mezzanine
      database_host: "10.1.1.7"
      live_hostname: 52.168.13.127.xip.io
      domains:
        - 52.168.13.127.xip.io
        - www.52.168.13.127.xip.io
